-d C:\Users\nguye\Documents\GitHub\gowin_riscv\impl\gwsynthesis\rmii.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\nguye\Documents\GitHub\gowin_riscv\src\rmii.cst
-cfg C:\Users\nguye\Documents\GitHub\gowin_riscv\impl\pnr\device.cfg
-sdc C:\Users\nguye\Documents\GitHub\gowin_riscv\src\rmii.sdc
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
